apiVersion: v1
kind: Pod
metadata:
  name: polinux-pod
spec:
  containers:
  - name: polinux-1
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
  - name: polinux-2
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
  - name: polinux-3
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
  - name: polinux-4
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
  - name: polinux-5
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
  - name: polinux-6
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "256M", "--vm-hang", "1"]
